### ISSUE TITLE
Initializing a scalar expression in @expression(s) returns Float64

### ISSUE THREAD

**Issue by daschw** [JuliaOpt/JuMP.jl#1000] opened 2017-03-26 14:12 UTC
Hi, I'm not sure if this really is an issue or if it is the intended behaviour, but to me it was somehow unexpected: 
If I do
```
using JuMP
m = Model()

@expression(m, x, 0.0)
```
then `typeof(x)` returns `Float64`. The same is true for the anonymous syntax `x = @expression(m, 0.0)`.

With
```
x = @expression(m, [1], 0.0)[1]
```
`typeof(x)` returns `JuMP.GenericAffExpr{Float64,JuMP.Variable}`, as I would have expected in all cases.

I know that I can also initialize an expression with `x = AffExpr()`, and it is not really an issue for me. I was just surprised.
(My use case was that I was initializing multiple expressions (some scalar, some vectors) with an `@expressions m begin ... end` block. I wanted to modify these expressions later with methods that accept `AffExpr` or `Vector{AffExpr}` as arguments. For the scalar expressions (being actually `Float64`s) I ran into a method error)

**Comment by mlubin** [comment] 2017-03-27 02:40
@daschw, congrats on opening JuMP issue 1000. If you email me your address I'll mail you some JuliaOpt stickers :)

The issue, however, is a duplicate of https://github.com/JuliaOpt/JuMP.jl/issues/525. We're planning on fixing this for JuMP 1.0. We have multiple types of expressions, so the array version of ``@expression`` should generate a collection that matches the expression types of the elements (which could be ``Float64`` if they are constants).

**Closed by mlubin** 2017-03-27 02:40 UTC

**Comment by daschw** [comment] 2017-03-27 07:30
OK, thanks ... and sorry for wasting issue 1000 on a duplicate ;)
