### ISSUE TITLE
Is OrderedDict required in the expressions types of would Dict be sufficent

### ISSUE THREAD

**Issue by ndinsmore** [JuliaOpt/JuMP.jl#1898] opened 2019-03-12 14:50 UTC
I am trying to go after low hanging fruit during the model creation process.  

Profiling the benchmark below it appears that the access to `OrderDict` has become a contributor to the time it takes to build a model.

We should be able to get a performace improvement by switching to a `Dict`, is there any reason not to?

```julia
using JuMP
using Clp
using GLPK
using BenchmarkTools
using Random
using SparseArrays
using Profile

function  build_model(solver, num_variables, num_constraints, density; opt_options::NamedTuple=NamedTuple())
    model = Model(with_optimizer(solver.Optimizer; opt_options...))
    rng=Random.MersenneTwister(1)

    sp_mat=sprand(rng,num_constraints,num_variables,density)
    vars=@variable(model,0<=vars[i=1:num_variables]<=0)

    cons=@constraint(model,cons,sp_mat * vars .== 0)
    return model
end
#-------
num_vars=100000
num_cons=10000
density=.001
#-----------
@benchmark optimize!(model) setup=(model=build_model(Clp,$num_vars,$num_cons,$density,opt_options=(LogLevel=0,MaximumSeconds=10.0)))

#-----
Profile.clear()
@profiler model=build_model(Clp,num_vars,num_cons,density,opt_options=(LogLevel=1,MaximumSeconds=10.0))
```

**Comment by mlubin** [comment] 2019-03-12 20:31
> We should be able to get a performace improvement by switching to a Dict, is there any reason not to?

Yes, we chose to use `OrderedDict` so that iteration through the expressions and the [conversion to MOI functions](https://github.com/JuliaOpt/JuMP.jl/blob/master/src/aff_expr.jl#L301-L307) is deterministic. It's essential that we can reproducibly pass the exact same model to Clp from given JuMP code.

**Comment by mlubin** [comment] 2019-03-14 12:15
Closing since the original question is answered.

**Closed by mlubin** 2019-03-14 12:15 UTC

**Comment by joaquimg** [comment] 2019-03-14 23:06
Related issue to speeding up this code https://github.com/JuliaLang/julia/issues/31199
