### ISSUE TITLE
@expression doesn't support index of type Array

### ISSUE THREAD

**Issue by adowling2** [JuliaOpt/JuMP.jl#955] opened 2017-02-01 21:03 UTC
This works:
```
I = 1:10
m = Model()
@expression(m, x[i=I], 0.0)
```

This does not:
`@expression(m, y[i = Array(I)], 0.0)`

`ERROR: MethodError: no method matching setindex!(::JuMP.JuMPArray{JuMP.GenericAffExpr{Float64,JuMP.Variable},1,Tuple{Array{Int64,1}}}, ::Float64, ::Int64)`

Yet this works:
`@variable(m, z[i = Array(I)])`

**Comment by mlubin** [comment] 2017-02-01 23:18
Thanks for the report. Pretty sure this is a duplicate of https://github.com/JuliaOpt/JuMP.jl/issues/949 and was fixed two days ago and already released in JuMP 0.15.1.

**Closed by mlubin** 2017-02-01 23:18 UTC
