### ISSUE TITLE
Constraint on absolute sum of PSD matrix not enforced correctly

### ISSUE THREAD

**Issue by ryancorywright** [JuliaOpt/JuMP.jl#2152] opened 2020-02-04 15:52 UTC
When adding a constraint on the absolute sum of a PSD matrix, the way JuMP handles symmetry causes the lower diagonal entries to be ignored in the constraint, meaning the constraint is not necessarily obeyed
E.g. if I run the following code (which computes an SDP relaxation of a sparse PCA problem)
```Julia
using JuMP, MosekTools, LinearAlgebra, Compat
pitprops=[[1,0.954,0.364,0.342,-0.129,0.313,0.496,0.424,0.592,0.545,0.084,-0.019,0.134];
       [0.954,1,0.297,0.284,-0.118,0.291,0.503,0.419,0.648,0.569,0.076,-0.036,0.144];
       [0.364,0.297,1,0.882,-0.148,0.153,-0.029,-0.054,0.125,-0.081,0.162,0.22,0.126];
       [0.342,0.284,0.882,1,0.22,0.381,0.174,-0.059,0.137,-0.014,0.097,0.169,0.015];
       [-0.129,-0.118,-0.148,0.22,1,0.364,0.296,0.004,-0.039,0.037,-0.091,-0.145,-0.208];
       [0.313,0.291,0.153,0.381,0.364,1,0.813,0.09,0.211,0.274,-0.036,0.024,-0.329];
       [0.496,0.503,-0.029,0.174,0.296,0.813,1,0.372,0.465,0.679,-0.113,-0.232,-0.424];
       [0.424,0.419,-0.054,-0.059,0.004,0.09,0.372,1,0.482,0.557,0.061,-0.357,-0.202];
       [0.592,0.648,0.125,0.137,-0.039,0.211,0.465,0.482,1,0.526,0.085,-0.127,-0.076];
       [0.545,0.569,-0.081,-0.014,0.037,0.274,0.679,0.557,0.526,1,-0.319,-0.368,-0.291];
       [0.084,0.076,0.162,0.097,-0.091,-0.036,-0.113,0.061,0.085,-0.319,1,0.029,0.007];
       [-0.019,-0.036,0.22,0.169,-0.145,0.024,-0.232,-0.357,-0.127,-0.368,0.029,1,0.184];
       [0.134,0.144,0.126,0.015,-0.208,-0.329,-0.424,-0.202,-0.076,-0.291,0.007,0.184,1];]
pitprops=reshape(pitprops, (13,13));
k=8
n=13
m=Model(with_optimizer(Mosek.Optimizer))

@variable(m, X[1:n, 1:n], PSD)

@variable(m, U[1:n, 1:n], Symmetric)

@constraint(m, X.<=U)

@constraint(m, -X.<=U)

@constraint(m, sum(U)<=k)

@constraint(m, sum(LinearAlgebra.diag(X))==1.0)

@objective(m, Max, Compat.dot(pitprops, X))

optimize!(m)

@show sum(abs.(value.(X)))
```

Gives an absolute sum of about 8.54>8; I have also tried telling JuMP that U is symmetric, but this actually yields the same behaviour.

This appears to be an issue with the way JuMP handles symmetry, because if I add the constraints 
```Julia
@constraint(m, X'.<=U)

@constraint(m, -X'.<=U)
```
then the absolute sum becomes 8, which is correct behaviour (based on this i'm assuming that it's an issue with JuMP rather than Mosek). 

I understand that ignoring the lower triangular constraints on X might be "optimal" in terms of obtaining the best possible performance from SDP solvers, but it also appears to silently return infeasible solutions. If the developers don't want to change the code base for performance reasons, would it be possible to warn the user if constraints on the lower triangular entries of X are silently violated?

For reference, my Julia package versions are:
JuMP v0.20.1
Mosek v1.1.1
MosekTools v0.9.1

Edit(odow): formatting

**Comment by odow** [comment] 2020-02-04 20:07
I get the correct answer with SCS so this is likely a MOSEK issue. It's not a bug in JuMP.

**Comment by odow** [comment] 2020-02-04 20:12
Confirmed as duplicate of #2102. Fixed on master.

Near-term work-around is to replace
```Julia
@constraint(m, X .<= U)
@constraint(m, -X .<= U)
```
with
```Julia
@constraint(m, 0 .<= U .- X)
@constraint(m, 0 .<= U .+ X)
```

**Closed** 2020-02-04 20:32 UTC
Labels: duplicate
