### ISSUE TITLE
memory issues with JuMP/Ipopt

### ISSUE THREAD

**Issue by gajjanag** [JuliaOpt/JuMP.jl#474] opened 2015-06-29 14:55 UTC
I am trying to run a medium scale nonlinear, nonconvex optimization problem with a dense Hessian (approximately 40 decision variables) using JuMP with Ipopt backend. Unfortunately, I run into huge memory issues - memory usage is stable around 3 GB for quite some time, but then all of a sudden shoots up to my physical memory capacity (8 GB), at which point thrashing occurs.
The code is pretty big, so I have kept it as a gist:

https://gist.github.com/gajjanag/97ecb4f452172d64d7d7

Method is invoked via: solve_model().

Package dependencies: JuMP, Ipopt, MathProgBase (obvious), Distributions.

**Comment by mlubin** [comment] 2015-06-29 18:58
Thanks for the test case, there definitely should't be such memory issues with a small model like this.

**Comment by mlubin** [comment] 2015-06-29 20:21
Could you try using the ``IpoptNLSolver()`` solver from the [AmplNLWriter](https://github.com/JackDunnNZ/AmplNLWriter.jl) package?

**Comment by gajjanag** [comment] 2015-06-29 20:39
Wow! That made a tremondous difference. Thanks a lot for this workaround!
As you might notice from my gist, my code is generated by a script, and the 20 there is a parameter.
So 20 caused the memory leak crashing the process on my machine, while 15 took nearly 1 hour to solve.
Using this modification, 20 is solved in less than a minute.
I suspect a large amount of memory allocations/gc cycles to be a culprit here.

**Comment by mlubin** [comment] 2015-06-29 21:05
You can thank @JackDunnNZ for the speedup :)
The performance issue could possibly be related to long strings of additions being slow in Julia. The JuMP code will be faster if you generate input data arrays and use ``sum{}`` instead of flattening out the additions, but equivalent models *should* perform the same, of course. This will happen in the next rewrite of JuMP's AD code.

**Comment by gajjanag** [comment] 2015-06-30 01:26
Turns out I reported too prematurely. The speedup is there, but the results are totally inaccurate. It seems like the affine constraint involving pA is not taken into account at all.

**Comment by mlubin** [comment] 2015-06-30 01:47
Could you report this issue with AmplNLWriter? You may also want to give https://github.com/JuliaOpt/CoinOptServices.jl a try.

**Comment by JackDunnNZ** [comment] 2015-06-30 02:01
Yes, the affine constraints are not yet handled by AmplNLWriter. It should work if you define them using @addNLConstraint

**Comment by mlubin** [comment] 2015-06-30 02:02
@JackDunnNZ, is that true even with a nonlinear objective?

**Comment by JackDunnNZ** [comment] 2015-06-30 02:33
Sorry, you are right, they do come through.

Everything seems to be generated correctly in the .nl file, and the solution I get with Bonmin satisfies the affine constraints. The solution by Ipopt does not satisfy the first constraint involving pA, as @gajjanag suggests. This isn't the first time Ipopt via AMPL has given bad solutions, the problem from @odow recently was the same. I wonder if it's a problem with the executable? Need to check this out more...

@gajjanag Can you try using the BonminNLSolver and see if that works. You will need https://github.com/JuliaOpt/CoinOptServices.jl if you don't have it already.

**Comment by gajjanag** [comment] 2015-06-30 03:22
I could not easily find a "BonminNLSolver". What I found was "OsilBonminSolver". Trying it out, I can only go up to n = 7, which is far worse than the original Ipopt (that made me create this issue). It effectively errors out with a "Not solved to optimality, Status = Infeasible" remark that clearly makes no sense (for n >= 8).

**Comment by JackDunnNZ** [comment] 2015-06-30 03:25
Sorry for not being clear, you can use `BonminNLSolver()` in place of `IpoptNLSolver()` as long as CoinOptServices has been added.

**Comment by gajjanag** [comment] 2015-06-30 03:41
That was actually my fault: I had removed the AmplNLWriter inclusion while adding the CoinOptServices inclusion.
Seems to work well so far (went up to n = 35).
THat brings me to a question, if I want to go to higher n (not relevant to this ticket):
For larger n, my coefficients go beyond the capacity of 64 bit numbers (largest coefficient is 3^n, and smallest is 1). There are two approaches I see:
1. Use BigInts - I do not know whether these optimization libraries accept BigInt's, and JuMP does not seem to document which ones do (if any).
2. Scale down coefficients to keep them as Floats. I am worried about the loss of precision.

**Comment by mlubin** [comment] 2015-06-30 03:52
Everything is already in ``Float64``, which can't represent large ``Int64`` coefficients exactly. I don't know of any nonlinear solvers which support higher precision, you'll probably have to start looking into custom methods. What's the significance of the solution here? Since you're maximizing a sum of convex functions, you're not guaranteed any global optimality by default.

**Comment by mlubin** [comment] 2015-06-30 03:53
(Actually not very clear if all the terms in the objective are convex)

**Comment by gajjanag** [comment] 2015-06-30 03:55
Yes, the problem is nonconvex, and each term is nonconvex as well. It is mainly as an exploratory exercise.

**Comment by JackDunnNZ** [comment] 2015-09-11 21:19
The issues with IpoptNLSolver should be resolved by JackDunnNZ/AmplNLWriter.jl@6472cdaeba714534ed80c1e63e18e11c7e3548d9

**Comment by mlubin** [comment] 2015-12-30 01:04
Will be fixed by #638, confirmed that there's no unusual memory usage

**Closed** 2016-01-11 22:29 UTC
Labels: NLP rewrite, nonlinear
