### ISSUE TITLE
variable lower/upper bound inconsistency

### ISSUE THREAD

**Issue by EdvinAblad** [JuliaOpt/JuMP.jl#1892] opened 2019-03-09 07:39 UTC
I am under the impression that a single variable has at most one lower and upper bound.

Hence, the code
```julia
m = Model(with_optimizer(Clp.Optimizer))
@variable(m, x)
@constraint(m, x in MOI.LessThan(7.0))
@constraint(m, x in MOI.LessThan(5.0))
@constraint(m, x in MOI.LessThan(10.0))
@objective(m, Max, x)
optimize!(m)
```

Is a little weird, and should probably warn the user about its behaviour. 
From the results (Clp and GLPK tested), it is only the last variable constraint that is used (seems like a sane choice).

1. `has_upper_bound(x)`  returns `false`, (It only seems to concern the bound introduced in `@variable` and not abound `@constraint` bounds)
2. `all_constraints(m, VariableRef, MOI.LessThan{Float64})` returns all three constraints
3. `value(x) ==10` returns `true` 

This is related to #1586, where it seems that `@constraint(m, x <= b) ` always introduces an affine constraint rather than a single variable constraint. Maybe this is the expected behaviour? 

At least this inconsistency is clearly a bug.

**Comment by mlubin** [comment] 2019-03-09 12:53
I believe this issue will be resolved by https://github.com/JuliaOpt/MathOptInterface.jl/issues/570, which would enforce that at most one variable bound can exist at a time.

**Comment by EdvinAblad** [comment] 2019-03-09 12:56
Sorry missed that ticket. 
I believe so too.

**Comment by holy-motors** [comment] 2019-05-07 22:03
I think the issue is resolved. Let's close this.

**Comment by mlubin** [comment] 2019-08-19 23:46
@holy-motors, agreed.

```julia
julia> m = Model();

julia> @variable(m, x)
x

julia> @constraint(m, x in MOI.LessThan(7.0))
x ≤ 7.0

julia> @constraint(m, x in MOI.LessThan(5.0))
ERROR: MathOptInterface.UpperBoundAlreadySet{MathOptInterface.LessThan{Float64},MathOptInterface.LessThan{Float64}}: Cannot add `SingleVariable`-in`MathOptInterface.LessThan{Float64}` constraint for variable MathOptInterface.VariableIndex(1) as a `SingleVariable`-in`MathOptInterface.LessThan{Float64}` constraint was already set for this variable and both constraints set an upper bound.
```

**Closed by mlubin** 2019-08-19 23:46 UTC
