### ISSUE TITLE
Modifying internal JuMP models via MPB

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#1005] opened 2017-04-12 21:26 UTC
This has come up a number of times (https://github.com/JuliaOpt/Gurobi.jl/issues/60#issuecomment-293646535) when a user builds a JuMP model, then modifies part of the underlying MPB level model. When the user solves the JuMP model, as lot of their changes get overwritten by https://github.com/JuliaOpt/JuMP.jl/blob/master/src/solvers.jl#L329-L334 and they end up solving a different problem to what they think they are solving.

For a Gurobi example here is a gist https://gist.github.com/odow/2dd99948fde8ae8bafc92f3f40d6aa2e

How do we discourage users from modifying internal JuMP models via MPB?

**Comment by mlubin** [comment] 2017-04-12 21:28
I wouldn't discourage this, it's partly by design. I'd rather make it more transparent what exactly JuMP does so that people can use MPB correctly.

**Comment by mlubin** [comment] 2017-04-12 21:29
Though it wouldn't hurt to check for consistency of problem dimensions between the JuMP model and the MPB model and print a warning if there's anything suspicious.

**Comment by mlubin** [comment] 2017-08-25 13:23
Closing since this will be resolved with MOI. While a JuMP model is attached to solver, all changes will be immediately reflected in the solver instance. What users decide to do to the solver instance is up to them.

**Closed by mlubin** 2017-08-25 13:23 UTC
