### ISSUE TITLE
Creating types that hold Model and NLExpressions

### ISSUE THREAD

**Issue by anriseth** [JuliaOpt/JuMP.jl#615] opened 2015-11-12 08:38 UTC
I'm trying to create a type with a set of parameters that define a Model with several NLExpressions. Then access these expressions from my instance(?) so that I can set different types of NLObjectives for my model to solve. 
When doing this I get a `LoadError`, see minimal example below.

Is there a different way to do what I'm trying to achieve here? I guess the problem is using the `@defNLExpr`  macro?

```julia
using JuMP, Ipopt

type MyModel
    m::Model
    x::JuMP.Variable
    expr

    function MyModel(param)
        m = Model()
        @defVar(m, x)
        @defNLExpr(expr, (x-param)*(x+param))

        new(m, x, expr)
    end
end

param = 1.0
mm = MyModel(param)

# Works
#@setNLObjective(mm.m, :Min, (mm.x-param)*(mm.x+param))
#solve(mm.m)

# Fails
@setNLObjective(mm.m, :Min, mm.expr)
solve(mm.m)
```

Throws the LoadError:
```
ERROR: LoadError: TypeError: eval_f: in typeassert, expected Float64, got ReverseDiffSparse.ParametricExpression{0}
 in eval_f at /home/asbjorn/.julia/v0.4/JuMP/src/nlp.jl:246
 in initialize at /home/asbjorn/.julia/v0.4/JuMP/src/nlp.jl:222
 in loadnonlinearproblem! at /home/asbjorn/.julia/v0.4/Ipopt/src/IpoptSolverInterface.jl:272
 in _buildInternalModel_nlp at /home/asbjorn/.julia/v0.4/JuMP/src/nlp.jl:540
 in buildInternalModel at /home/asbjorn/.julia/v0.4/JuMP/src/solvers.jl:186
 in solve at /home/asbjorn/.julia/v0.4/JuMP/src/solvers.jl:77
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
while loading /tmp/testtype.jl, in expression starting on line 26
```

**Comment by mlubin** [comment] 2015-11-12 16:51
This is essentially a duplicate of https://github.com/JuliaOpt/JuMP.jl/issues/567. A possible way to restructure it is to instead pass around functions that set the objective, e.g.,

```julia
function foo1(m, param)
    x = getVar(m, :x)
    @setNLObjective(m, (x-param)*(x+param))
end
function foo2(...)
    ...
end
```
And then conditionally decide whether to use ``foo1`` or ``foo2``.

**Comment by anriseth** [comment] 2015-11-12 18:00
Okay; I felt like I'd seen this issue before somewhere:p I'll just have to stick with lots of copy-paste code for now.

To get the context, which might be useful for the NLP rewrite: 
I'm experimenting with different multi-objective optimisation methods. So I want the flexibility to set convex combinations of NLExpressions foo1 and foo2 as objectives, set foo1 as an objective and foo2 as a constraint and vice-versa. Or even use foo1 and foo2 in constraints (like the Normal Boundary Intersection method).

**Comment by mlubin** [comment] 2015-11-15 19:57
@anriseth, that should be possible after the rewrite. Closing this issue as a duplicate

**Closed by mlubin** 2015-11-15 19:57 UTC
Labels: NLP rewrite

**Comment by anriseth** [comment] 2015-11-15 21:38
That's great.
@mlubin I'd like to help out with the NLP rewrite. If I can make myself useful by doing some testing or coding, let me know.

**Comment by mlubin** [comment] 2015-11-16 02:38
@anriseth, thanks! The bulk of the effort is going into rewriting the automatic differentiation code, after which we need to rewrite how JuMP constructs and stores nonlinear expression objects. There's certainly a lot of room for help in the second part.
