### ISSUE TITLE
Failed to precompile JuMP

### ISSUE THREAD

**Issue by poulson** [JuliaOpt/JuMP.jl#939] opened 2017-01-18 05:10 UTC
From a fresh build of `git HEAD` of Julia:
```
julia> Pkg.add("JuMP")
INFO: Initializing package repository /home/poulson/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of Calculus from https://github.com/johnmyleswhite/Calculus.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of DataStructures from https://github.com/JuliaLang/DataStructures.jl.git
INFO: Cloning cache of DiffBase from https://github.com/JuliaDiff/DiffBase.jl.git
INFO: Cloning cache of ForwardDiff from https://github.com/JuliaDiff/ForwardDiff.jl.git
INFO: Cloning cache of JuMP from https://github.com/JuliaOpt/JuMP.jl.git
INFO: Cloning cache of Lazy from https://github.com/MikeInnes/Lazy.jl.git
INFO: Cloning cache of MacroTools from https://github.com/MikeInnes/MacroTools.jl.git
INFO: Cloning cache of MathProgBase from https://github.com/JuliaOpt/MathProgBase.jl.git
INFO: Cloning cache of NaNMath from https://github.com/mlubin/NaNMath.jl.git
INFO: Cloning cache of ReverseDiffSparse from https://github.com/mlubin/ReverseDiffSparse.jl.git
INFO: Installing Calculus v0.1.15
INFO: Installing Compat v0.12.0
INFO: Installing DataStructures v0.5.1
INFO: Installing DiffBase v0.0.2
INFO: Installing ForwardDiff v0.3.3
INFO: Installing JuMP v0.15.0
INFO: Installing Lazy v0.11.5
INFO: Installing MacroTools v0.3.4
INFO: Installing MathProgBase v0.5.10
INFO: Installing NaNMath v0.2.2
INFO: Installing ReverseDiffSparse v0.6.0
INFO: Package database updated

julia> using JuMP
INFO: Precompiling module JuMP.
WARNING: Array{T}(::Type{T},m::Int) is deprecated, use Array{T,1}(m) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] Array(::Type{Tuple{Symbol,Expr}}, ::Int64) at ./deprecated.jl:50
 [3] include_from_node1(::String) at ./loading.jl:532
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:532
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
 [8] eval(::Module, ::Any) at ./boot.jl:238
 [9] process_options(::Base.JLOptions) at ./client.jl:285
 [10] _start() at ./client.jl:374
while loading /home/poulson/.julia/v0.6/Calculus/src/differentiate.jl, in expression starting on line 198
WARNING: Method definition exp(ForwardDiff.Dual{N, T} where T<:Real) in module ForwardDiff at /home/poulson/.julia/v0.6/ForwardDiff/src/dual.jl:311 overwritten at /home/poulson/.julia/v0.6/ForwardDiff/src/dual.jl:336.
WARNING: Method definition sqrt(ForwardDiff.Dual{N, T} where T<:Real) in module ForwardDiff at /home/poulson/.julia/v0.6/ForwardDiff/src/dual.jl:311 overwritten at /home/poulson/.julia/v0.6/ForwardDiff/src/dual.jl:341.
WARNING: Method definition exp(ForwardDiff.Dual{N, T} where T<:Real where N) in module ForwardDiff at /home/poulson/.julia/v0.6/ForwardDiff/src/dual.jl:336 overwritten at /home/poulson/.julia/v0.6/ForwardDiff/src/dual.jl:311.
WARNING: Method definition sqrt(ForwardDiff.Dual{N, T} where T<:Real where N) in module ForwardDiff at /home/poulson/.julia/v0.6/ForwardDiff/src/dual.jl:341 overwritten at /home/poulson/.julia/v0.6/ForwardDiff/src/dual.jl:311.
ERROR: LoadError: LoadError: ArgumentError: method definition for Type at /home/poulson/.julia/v0.6/DataStructures/src/hash_dict.jl:72 has free type variables
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:532
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:532
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/poulson/.julia/v0.6/DataStructures/src/hash_dict.jl, in expression starting on line 72
while loading /home/poulson/.julia/v0.6/DataStructures/src/DataStructures.jl, in expression starting on line 70
ERROR: LoadError: LoadError: Failed to precompile DataStructures to /home/poulson/.julia/lib/v0.6/DataStructures.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:666
 [2] require(::Symbol) at ./loading.jl:424
 [3] include_from_node1(::String) at ./loading.jl:532
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:532
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /home/poulson/.julia/v0.6/ReverseDiffSparse/src/coloring.jl, in expression starting on line 3
while loading /home/poulson/.julia/v0.6/ReverseDiffSparse/src/ReverseDiffSparse.jl, in expression starting on line 16
ERROR: LoadError: Failed to precompile ReverseDiffSparse to /home/poulson/.julia/lib/v0.6/ReverseDiffSparse.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:666
 [2] require(::Symbol) at ./loading.jl:424
 [3] include_from_node1(::String) at ./loading.jl:532
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/poulson/.julia/v0.6/JuMP/src/JuMP.jl, in expression starting on line 21
ERROR: Failed to precompile JuMP to /home/poulson/.julia/lib/v0.6/JuMP.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:666
 [2] require(::Symbol) at ./loading.jl:453
```

**Comment by blegat** [comment] 2017-01-18 09:21
Thanks for reporting this issue. It seems that this is caused by [DataStructures](https://github.com/JuliaLang/DataStructures.jl) which does not work with Julia v0.6, I would advice you to report it there.

**Comment by mlubin** [comment] 2017-01-18 14:03
It will be a bit before JuMP and all of its dependencies catch up with the breaking changes in 0.6. See, e.g., https://github.com/JuliaOpt/MathProgBase.jl/pull/150.

**Comment by mlubin** [comment] 2017-01-31 13:29
The precompile issue was fixed by https://github.com/JuliaOpt/JuMP.jl/pull/951. There's more to do to get things working on 0.6, but that will happen anyway so no need to leave an issue open.

**Closed by mlubin** 2017-01-31 13:29 UTC
