### ISSUE TITLE
Style for naming model

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1885] opened 2019-03-02 16:44 UTC
We should mention in the style guide that the model should be named `model` instead of `m` as the variable name is more representative with `model`.

**Comment by mlubin** [comment] 2019-03-02 17:42
This should be generalized into a discussion about using meaningful names rather than a special discussion on `m` vs. `model`.

**Comment by mlubin** [comment] 2019-03-02 17:43
This is a duplicate of https://github.com/JuliaOpt/JuMP.jl/issues/1780.

**Comment by barpit20** [comment] 2019-03-02 17:47
Sorry @mlubin I had not read your comments before sending the PR

**Comment by blegat** [comment] 2019-03-04 11:27
Closing as it's a duplicate

**Closed** 2019-03-04 11:27 UTC
Labels: docs
