### ISSUE TITLE
Hygiene is still broken on 1.0

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1522] opened 2018-10-06 13:52 UTC
```julia
using JuMP, GLPK

pH = 1/2
pL = 1 - pH
vH = 2/3
vL = 1/3

sigL = [1/3 1/3 1/3]
sigH = [1/3 1/3 1/3]
model = Model(with_optimizer(GLPK.Optimizer))
@variable(model,0 <= xH <= 1)
@variable(model,0 <= tH <= 1)
@variable(model,xL[1:length(sigL)],Bin)
@variable(model,tL[1:length(sigL)],Bin)

@constraint(model,ICH,vH*xH - tH >= sum(sigH[i]*(vH * xL[i] - tL[i]) for i in 1:length(sigH)))
@objective(model,Max,pH * tH + pL * sum(sigL[i]*tL[i] for i in 1:length(sigL)))
```

The last two lines both give undefined variable errors. Reported by @carlocab in https://discourse.julialang.org/t/undefvarerror-in-jump-constraint/15701 and https://github.com/JuliaOpt/JuMP.jl/pull/1517#issuecomment-427569227.

**Comment by blegat** [comment] 2018-10-08 08:05
@carlocab I have just tried on master and I cannot reproduce the problem. Can you confirm that this is failing on master ?

**Comment by carlocab** [comment] 2018-10-08 11:29
You're right -- this problem is fixed on master. It seems that `] dev JuMP` apparently does _not_ check out the master branch for some reason, which is why I encountered the error again after your PR was merged. My mistake; apologies for that.

**Comment by blegat** [comment] 2018-10-08 11:32
`] dev JuMP` has effect only once. Once `~/.julia/dev/JuMP` already exists, it is never touched again by the package manager

**Closed by blegat** 2018-10-08 11:32 UTC

**Comment by mlubin** [comment] 2018-10-08 12:16
Weird. I definitely checked out the latest `master`, but I guess `Pkg` was not in a good state.

**Comment by carlocab** [comment] 2018-10-08 12:44
> `] dev JuMP` has effect only once. Once `~/.julia/dev/JuMP` already exists, it is never touched again by the package manager

Yes, I ran `rm -rf ~/.julia/dev/JuMP` before  `] dev JuMP` when I tested it, to make sure that I checked out the latest branch. That still produced the error. `] add JuMP#master` did not.
