### ISSUE TITLE
Add inexplicit indexing warning when adding constraints

### ISSUE THREAD

**Issue by jac0320** [JuliaOpt/JuMP.jl#937] opened 2017-01-13 17:48 UTC
So I was using a 3-dimensional variable, when adding constraints, I use the sum() generator and gave an explicit indexing with two indices, it automatically assumed the third index to be 1. It could be challenging in debugging the model especially when a complex variable is given.

Do you think it is necessary to have a warning message to notify users for implied index?

julia> @variable(m, x[1:5,1:5,1:10], Bin);

julia> @constraint(m, sum(x[i,j] for i=1:3, j=1:2)>=4)
x[1,1,1] + x[1,2,1] + x[2,1,1] + x[2,2,1] + x[3,1,1] + x[3,2,1] ≥ 4

Thanks.

**Comment by mlubin** [comment] 2017-01-13 17:51
Thanks for the report. This is a duplicate of https://github.com/JuliaOpt/JuMP.jl/issues/653 which goes back to an upstream issue in Julia.

**Closed by mlubin** 2017-01-13 17:51 UTC
