### ISSUE TITLE
value function very slow 

### ISSUE THREAD

**Issue by ndinsmore** [JuliaOpt/JuMP.jl#1826] opened 2019-02-04 20:58 UTC
I have noticed that in master value is much slower than you would expect it to be.  Certainly this is related to the issue #1824 that @odow but I wanted to capture the user level issue.

I have created a benchmark to document that is essentially a min cost flow problem on a graph with 2000 nodes and 30000 edges. 

With this benchmark and simply using the time function value is 10x slower than optimize and it dominates the run time of the benchmark.   Below are the results with the first two lines being the individual functions and the bottom line is to total time of the function which included the other two.
```
optimize!:    0.921537 seconds (3.53 M allocations: 123.136 MiB, 38.95% gc time)
value:           5.996989 seconds (507.56 k allocations: 6.666 GiB, 20.98% gc time)
  7.316544 seconds (5.10 M allocations: 6.869 GiB, 23.65% gc time)
```

```julia
using JuMP
using Random
using SparseArrays
using Cbc

#------
rng=Random.MersenneTwister(1)
num_verts=nv=2000
num_edges=ne=nv*15

num_source_sink=Int64(ceil(nv*0.05))

#randomly create the sources and sinks
rand_source_sink=randperm(rng,nv)[1:2*num_source_sink]
node_demand=spzeros(nv)
node_demand[rand_source_sink]=repeat([1.0,-1.0],num_source_sink)

#create the edge cost martix
CI=rand(rng,1:nv,ne);    CJ=rand(rng,1:nv,ne);  CV=rand(rng,ne)
C=sparse(CI,CJ,CV,nv,nv)
#-------

#Sparse cost matrix represents the graph as well
function jump_mincost_flow(edge_cost_mat::SparseMatrixCSC,
        node_demand::AbstractVector,
        edge_capacity::Float64
        )
    model = Model(with_optimizer(Cbc.Optimizer))

    I,J,edge_costs=findnz(edge_cost_mat)
    nv = size(edge_cost_mat,1)
    ne = length(I)

    #Creation of edge to node matrix
    AI=Vector{Int64}(undef,ne*2);    AJ=Vector{Int64}(undef,ne*2)
    AV=Vector{Float64}(undef,ne*2)
    inds=1:2:2*ne;    AI[inds]=I;    AJ[inds]=1:ne;    AV[inds].=1.0;
    inds=2:2:2*ne;    AI[inds]=J;    AJ[inds]=1:ne;    AV[inds].=-1.0;
    A=sparse(AI,AJ,AV,nv,ne)

    @variable(model, 0<= x[i=1:ne] <= edge_capacity)
    @objective(model, Min, sum(edge_costs .* x))
    @constraint(model, A * x .== node_demand)

    print("optimize!:  "); @time redirect_stdout((()->optimize!(model)),open("/dev/null", "w"))

    print("value:      "); @time edge_flows=value.(x)
    sol_sparse = sparse(view(AI,1:2:2*ne),view(AI,2:2:2*ne),edge_flows,nv,nv)
    return sol_sparse
end
#------
#force the JIT
redirect_stdout((()->jump_mincost_flow(C,node_demand,Float64(num_source_sink))),open("/dev/null", "w"))
#------
@time jump_mincost_flow(C,node_demand,Float64(num_source_sink))
```

Edit(odow): formatting.

**Comment by odow** [comment] 2019-02-04 21:53
I can't reproduce the difference with GLPK. This seems like it might be a CBC issue. The likely culprit is that the wrapper looks up the entire solution vector for every variable, rather than caching it. See:

https://github.com/JuliaOpt/Cbc.jl/blob/489db0680e71c6ce4f61b991afb1241864923d24/src/MOI_wrapper.jl#L347-L352

**Comment by odow** [comment] 2019-02-04 22:10
Closing in favor of a CBC specific issue: https://github.com/JuliaOpt/Cbc.jl/issues/102

**Closed by odow** 2019-02-04 22:10 UTC
