### ISSUE TITLE
Address TODO in test/variable.jl

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#1448] opened 2018-08-30 04:00 UTC
```
    # TODO: Decide what to do here.
    # @testset "getstart on sparse array (#889)" begin
    #     model = ModelType()
    #     @variable(model, x)
    #     @variable(model, y)
    #     X = sparse([1, 3], [2, 3], [x, y])
    #
    #     @test typeof(X) == SparseMatrixCSC{VariableRefType, Int}
    #
    #     setstart(x, 1)
    #     setstart(y, 2)
    #
    #     Y = getstart.(X)
    #     @test typeof(Y) == SparseMatrixCSC{Float64, Int}
    #     @test Y == sparse([1, 3], [2, 3], [1, 2])
    # end
```

Seems to have been introduced early in MOI days.

**Comment by odow** [comment] 2018-11-15 01:53
FWIW, the current error is this:
```julia
using JuMP
using SparseArrays
m = Model()
@variable(m, x)
@variable(m, y)
JuMP.set_start_value(x, 1)
JuMP.set_start_value(y, 2)
X = sparse([1,3], [2,3], [x, y])
JuMP.start_value.(X)
```
```julia
ERROR: MethodError: no method matching start_value(::JuMP.GenericAffExpr{Float64,VariableRef})
Closest candidates are:
start_value(::VariableRef) at C:\Users\Oscar\.julia\packages\JuMP\37prn\src\variables.jl:533
Stacktrace:
[1] _noshapecheck_map(::typeof(JuMP.start_value), ::SparseMatrixCSC{VariableRef,Int64}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SparseArrays\src\higherorderfns.jl:155
[2] copy(::Base.Broadcast.Broadcasted{SparseArrays.HigherOrderFns.SparseMatStyle,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},typeof(JuMP.start_value),Tuple{SparseMatrixCSC{VariableRef,Int64}}}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SparseArrays\src\higherorderfns.jl:165
[3] materialize(::Base.Broadcast.Broadcasted{SparseArrays.HigherOrderFns.SparseMatStyle,Nothing,typeof(JuMP.start_value),Tuple{SparseMatrixCSC{VariableRef,Int64}}}) at .\broadcast.jl:724
[4] top-level scope at none:0
```
I guess broadcasting over sparse arrays is weird somehow which causes the variables to get promoted to `GenericAffExpr`.

**Comment by blegat** [comment] 2018-11-15 08:16
That's another argument for defining value, dual and start_value for containers. There is also the issue with broadcast not working on Dict

**Comment by odow** [comment] 2018-12-20 21:19
So the issue is that accessing an empty element like `X[1, 1]` returns `zero(VariableRef)` which is the `GenericAffExpr` `0.0`.

One hacky way to fix this is to define
```julia
JuMP.start_value(::typeof(zero(JuMP.VariableRef))) = 0.0
```
But then we probably need to do similar things for `JuMP.value` etc.

An easier course of action is just to say that weird container types are not JuMP's business and to close this issue.

**Comment by blegat** [comment] 2018-12-21 08:44
The missing entries of a SparseMatrixCSC are meant to be zero so if someone broadcast a function on such arrays it should be applyable on zero which is not the case here. To use a sparse array where missing entries are treated as not part of the array one should use `Containers.SparseAxisArray`.
So I don't think there is anything to do here

**Closed** 2018-12-22 03:16 UTC
