### ISSUE TITLE
"Key not found" error with colons

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#643] opened 2016-01-11 02:09 UTC
```
julia> m = Model()
julia> @defVar(m, x[i=1:5,j=1:5,k=0:j])
julia> x[:,1,0]
ERROR: KeyError: (Colon(),1,0) not found
 in getindex at /Users/idunning/.julia/v0.4/JuMP/src/JuMPContainer.jl:48
```

We should probably be providing a better error message here

**Comment by mlubin** [comment] 2016-01-12 00:03
We can fix https://github.com/JuliaOpt/JuMP.jl/issues/287 now

**Comment by joehuchette** [comment] 2016-01-12 02:52
FWIW:
```jl
julia> @defVar(m, x[i=1:5,j=1:5,k=0:5]);

julia> x[:,1,0]
ERROR: MethodError: `isless` has no method matching isless(::Colon, ::Int64)
Closest candidates are:
  isless(::AbstractFloat, ::Real)
  isless(::Real, ::Real)
  isless(::Char, ::Integer)
  ...
 in getindex at /Users/huchette/.julia/v0.4/JuMP/src/JuMPArray.jl:61
```

**Comment by mlubin** [comment] 2016-03-03 02:03
We can give a better error message here, if we assume that nobody would use ``[Colon()]`` as an index set...

**Comment by joehuchette** [comment] 2016-03-03 02:13
Well we can always make
```jl
S = [Colon()]
@defVar(m, x[S])
```
an error...

**Comment by joehuchette** [comment] 2016-05-23 20:21
It's weird, but I'm not sure we can disambiguate the case @IainNZ mentions and this one:
```jl
julia> @defVar(m, y[[:]]);

julia> y[:]
1-element Array{JuMP.Variable,1}:
 y[Colon()]
```

**Comment by mlubin** [comment] 2016-05-31 18:28
@joehuchette, not sure I understand. Can we disambiguate it if we disallow colons in keys?

**Comment by joehuchette** [comment] 2016-05-31 22:14
I guess? Seems kinda arbitrary and brittle

**Comment by mlubin** [comment] 2016-05-31 22:15
Not having slicing work is also brittle and seemingly arbitrary since it works for some kinds of JuMP variables and not others.

**Comment by joehuchette** [comment] 2016-06-01 02:01
It's certainly less brittle to reliably throw an error than give completely unexpected behavior if you use a ``:`` or ``Colon()`` in your index set for some reason. I'm open to the idea of allowing slices for JuMPDicts, but I don't think the implementation will be particularly straightforward.

**Closed** 2017-11-25 03:49 UTC
Labels: JuMPContainer
