### ISSUE TITLE
Travis error in another package: ERROR: ReverseDiffSparse not defined

### ISSUE THREAD

**Issue by tshort** [JuliaOpt/JuMP.jl#387] opened 2015-02-08 23:44 UTC
In the [Sims.jl package](https://github.com/tshort/Sims.jl), we use JuMP as an option to solve for initial conditions in our system of DAE's. Recently, Travis has been complaining with the following error that looks JuMP related: "ERROR: ReverseDiffSparse not defined". See here:

https://travis-ci.org/tshort/Sims.jl/builds/49911361#L3551-L3560 

All tests pass locally for me (julia-release) and for @iraikov (including the JuMP tests). Any ideas on what could be causing that.

(By the way, JuMP is awesome! That package along with the whole JuliaOpt infrastructure looks like a killer application for Julia.)

**Comment by joehuchette** [comment] 2015-02-09 00:37
Not completely sure what's going on, but if I had to guess it would be some strange scoping behavior introduced in [this line](https://github.com/tshort/Sims.jl/blob/7597067332d6463970e56484a79fc7ca22d78ac3/src/utils.jl#L499). Strange you can't reproduce locally, though. CCing @mlubin.

BTW I pulled Sims on both julia v0.3 and v0.4 and I got this failure in ``Pkg.test("Sims")``:
```
ERROR: LoadError: DASKR failed prematurely
 in dasslsim at /Users/huchette/.julia/v0.4/Sims/src/dassl.jl:178
 in dasslsim at /Users/huchette/.julia/v0.4/Sims/src/dassl.jl:187
 in runexamples at /Users/huchette/.julia/v0.4/Sims/src/../examples/lib/Lib.jl:45
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:319
 in _start at ./client.jl:403
while loading /Users/huchette/.julia/v0.4/Sims/test/runtests.jl, in expression starting on line 6
```

**Comment by tshort** [comment] 2015-02-09 00:46
The line you mentioned is quite clunky, but it has worked so far to create a constraint based on an expression.

Thanks for the report on the test failures. I've seen intermittent failures there, but I'm not sure of the cause.

**Comment by mlubin** [comment] 2015-02-09 05:48
Looks like it may be a hygiene issue in ``@addNLConstraint``. I made a number of recent changes to ReverseDiffSparse which could cause this.

**Comment by tshort** [comment] 2015-02-09 12:39
I've reproduced it locally, so I can play with it, now.

**Comment by tshort** [comment] 2015-02-09 13:31
Here's a smaller example:

```julia
# works
using JuMP
m = JuMP.Model()
JuMP.@defVar(m, y[1:3])
ex = :(y[1] == 33.0)
eval(:( _f(y, m) = JuMP.@addNLConstraint(m, $ex) ))
_f(y,m)

# works
module MyMod
using JuMP, ReverseDiffSparse
m = JuMP.Model()
JuMP.@defVar(m, y[1:3])
ex = :(y[1] == 33.0)
eval(:( _f(y, m) = JuMP.@addNLConstraint(m, $ex) ))
_f(y,m)
end

# broken
module MyMod
using JuMP
m = JuMP.Model()
JuMP.@defVar(m, y[1:3])
ex = :(y[1] == 33.0)
eval(:( _f(y, m) = JuMP.@addNLConstraint(m, $ex) ))
_f(y,m)
end

```
It gives me a workaround anyway.

**Comment by mlubin** [comment] 2015-02-09 16:41
Tagged a new version of ReverseDiffSparse, should be fixed now.

**Closed by mlubin** 2015-02-09 16:41 UTC
