### ISSUE TITLE
Error running getInternalModel() in REPL

### ISSUE THREAD

**Issue by ashwincarvalho** [JuliaOpt/JuMP.jl#608] opened 2015-11-02 20:03 UTC
I was trying to access the low-level model (in an effort to get more solver stats), but ran into some issues while running this in the REPL:
```
m = Model(solver=IpoptSolver())
@defVar(m, x)
@setNLObjective(m, Min, x^3)
buildInternalModel(m)
internalModel = JuMP.getInternalModel(m)
```
Here's the error:
```
ERROR: UndefRefError: access to undefined reference
 in show at show.jl:72
 in show_default at show.jl:33
 in show at show.jl:7
 in show_default at show.jl:33
 in show at show.jl:7
 in anonymous at show.jl:1278
 in with_output_limit at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in showlimited at show.jl:1277
 in writemime at replutil.jl:4
 in display at REPL.jl:115
 in display at REPL.jl:118
 [inlined code] from multimedia.jl:151
 in display at multimedia.jl:162
 in print_response at REPL.jl:135
 in print_response at REPL.jl:122
 in anonymous at REPL.jl:624
 in run_interface at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_frontend at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_repl at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
```
It works if I run the script via the command line.

**Comment by mlubin** [comment] 2015-11-02 22:47
I think this is just a printing issue. A workaround is to put a semicolon at the end of the line to avoid trying to print out the ``internalModel``.

**Comment by ashwincarvalho** [comment] 2015-11-02 22:49
Oh, my bad. Didn't look at the error message closely!

**Comment by mlubin** [comment] 2015-11-02 22:50
It's worth fixing if possible, leaving open.

**Comment by joehuchette** [comment] 2015-11-03 00:40
I can't reproduce this on JuMP master. Could you post the versions of packages you are using? (Pkg.status)

**Comment by ashwincarvalho** [comment] 2015-11-03 00:55
```
julia> Pkg.status()
6 required packages:
 - Atom                          0.1.1
 - IJulia                        1.1.8
 - Ipopt                         0.1.18
 - JuMP                          0.10.2
 - MathProgBase                  0.3.19
 - PyPlot                        2.1.1
32 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.19
 - Calculus                      0.1.14
 - CodeTools                     0.1.0
 - ColorTypes                    0.1.7
 - Colors                        0.5.4
 - Compat                        0.7.7
 - Conda                         0.1.7
 - DataStructures                0.3.13
 - Dates                         0.4.4
 - Docile                        0.5.19
 - DualNumbers                   0.1.5
 - FactCheck                     0.4.1
 - FixedPointNumbers             0.0.12
 - Hiccup                        0.0.1
 - Homebrew                      0.1.17
 - JSON                          0.5.0
 - JuliaParser                   0.6.3+             master
 - LNR                           0.0.1
 - LaTeXStrings                  0.1.6
 - Lazy                          0.10.1
 - MacroTools                    0.2.0
 - Media                         0.1.1
 - NaNMath                       0.1.1
 - Nettle                        0.2.0
 - PyCall                        1.1.2
 - Reexport                      0.0.3
 - Requires                      0.2.0
 - ReverseDiffSparse             0.2.11
 - SHA                           0.1.2
 - URIParser                     0.1.1
 - ZMQ                           0.3.0
```

**Comment by joehuchette** [comment] 2015-11-05 05:36
I still can't reproduce this. Maybe update from v0.4-rc1 to a true release?

**Comment by ashwincarvalho** [comment] 2015-11-05 19:13
Yes, I don't get any errors with v0.4.0.

**Comment by joehuchette** [comment] 2015-11-05 19:47
Cool. I'm closing this, reopen if the issue resurfaces.

**Closed by joehuchette** 2015-11-05 19:47 UTC
