### ISSUE TITLE
test JuMP fails on 0.7

### ISSUE THREAD

**Issue by ufechner7** [JuliaOpt/JuMP.jl#1379] opened 2018-07-27 20:42 UTC
I am using Julia 0.7 master as of today on Ubuntu 16.04.
Installing JuMP@master works, precompiling and using it also works, but the tests fail:
```
(v0.7) pkg> test JuMP
   Testing JuMP
 Resolving package versions...
 Installed DualNumbers ─ v0.4.0
  Updating `/tmp/tmpWXAVoY/Project.toml`
  [7d9fca2a] - Arpack v0.1.4
  [9e28174c] + BinDeps v0.8.8
  [b99e7846] + BinaryProvider v0.3.3
  [49dc2e85] + Calculus v0.4.0
  [bbf7d656] + CommonSubexpressions v0.2.0
  [34da2185] + Compat v1.0.0
  [864edb3b] + DataStructures v0.10.0
  [163ba53b] + DiffResults v0.0.3
  [b552c78f] + DiffRules v0.0.6
  [fa6b7ba4] + DualNumbers v0.4.0
  [f6369f11] + ForwardDiff v0.7.5
  [b8f27783] + MathOptInterface v0.4.1
  [77ba4419] + NaNMath v0.3.1
  [6fe1bfb0] + OffsetArrays v0.8.0
  [276daf66] + SpecialFunctions v0.6.0
  [90137ffa] + StaticArrays v0.8.2
  [30578b45] + URIParser v0.3.1
  Updating `/tmp/tmpWXAVoY/Manifest.toml`
  [fa6b7ba4] + DualNumbers v0.4.0
  [6fe1bfb0] + OffsetArrays v0.8.0
WARNING: Base.scale! is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
  likely near /home/ufechner/.julia/packages/JuMP/zqYp/src/utils.jl:31
WARNING: Base.dropzeros is deprecated: it has been moved to the standard library package `SparseArrays`.
Add `using SparseArrays` to your imports.
  likely near /home/ufechner/.julia/packages/JuMP/zqYp/src/affexpr.jl:182
WARNING: Base.dropzeros is deprecated: it has been moved to the standard library package `SparseArrays`.
Add `using SparseArrays` to your imports.
  likely near /home/ufechner/.julia/packages/JuMP/zqYp/src/quadexpr.jl:138
WARNING: importing deprecated binding Base.gamma into Derivatives.
Internal error: encountered unexpected error in runtime:
ErrorException("type Nothing has no field args")
rec_backtrace at /home/ufechner/julia/src/stackwalk.c:94
record_backtrace at /home/ufechner/julia/src/task.c:246
jl_throw at /home/ufechner/julia/src/task.c:577
jl_errorf at /home/ufechner/julia/src/rtutils.c:77
jl_field_index at /home/ufechner/julia/src/datatype.c:821
jl_f_getfield at /home/ufechner/julia/src/builtins.c:755
try_compute_fieldidx_expr at ./compiler/ssair/passes.jl:23
getfield_elim_pass! at ./compiler/ssair/passes.jl:720
run_passes at ./compiler/ssair/driver.jl:123
optimize at ./compiler/optimize.jl:162
typeinf at ./compiler/typeinfer.jl:35
typeinf_ext at ./compiler/typeinfer.jl:567
typeinf_ext at ./compiler/typeinfer.jl:604
jfptr_typeinf_ext_58 at /home/ufechner/julia/usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /home/ufechner/julia/src/gf.c:2165
jl_apply at /home/ufechner/julia/src/julia.h:1538 [inlined]
jl_apply_with_saved_exception_state at /home/ufechner/julia/src/rtutils.c:257
jl_type_infer at /home/ufechner/julia/src/gf.c:275
jl_compile_method_internal at /home/ufechner/julia/src/gf.c:1767 [inlined]
jl_fptr_trampoline at /home/ufechner/julia/src/gf.c:1811
jl_apply_generic at /home/ufechner/julia/src/gf.c:2165
macro expansion at /home/ufechner/.julia/packages/JuMP/zqYp/test/derivatives.jl:40 [inlined]
macro expansion at /home/ufechner/julia/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1080 [inlined]
top-level scope at /home/ufechner/.julia/packages/JuMP/zqYp/test/derivatives.jl:11
jl_fptr_trampoline at /home/ufechner/julia/src/gf.c:1812
jl_toplevel_eval_flex at /home/ufechner/julia/src/toplevel.c:825
jl_parse_eval_all at /home/ufechner/julia/src/ast.c:841
jl_load at /home/ufechner/julia/src/toplevel.c:865
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1050
include at ./sysimg.jl:29
jl_apply_generic at /home/ufechner/julia/src/gf.c:2165
include at ./client.jl:393
jl_apply_generic at /home/ufechner/julia/src/gf.c:2165
do_call at /home/ufechner/julia/src/interpreter.c:324
eval_value at /home/ufechner/julia/src/interpreter.c:428
eval_stmt_value at /home/ufechner/julia/src/interpreter.c:363 [inlined]
eval_body at /home/ufechner/julia/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /home/ufechner/julia/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f41be84028f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /home/ufechner/julia/src/interpreter.c:808
jl_toplevel_eval_flex at /home/ufechner/julia/src/toplevel.c:831
jl_parse_eval_all at /home/ufechner/julia/src/ast.c:841
jl_load at /home/ufechner/julia/src/toplevel.c:865
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1050
include at ./sysimg.jl:29
jl_apply_generic at /home/ufechner/julia/src/gf.c:2165
include at ./client.jl:393
jl_fptr_trampoline at /home/ufechner/julia/src/gf.c:1812
jl_apply_generic at /home/ufechner/julia/src/gf.c:2165
do_call at /home/ufechner/julia/src/interpreter.c:324
eval_value at /home/ufechner/julia/src/interpreter.c:428
eval_stmt_value at /home/ufechner/julia/src/interpreter.c:363 [inlined]
eval_body at /home/ufechner/julia/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /home/ufechner/julia/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f41e345e85f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /home/ufechner/julia/src/interpreter.c:808
jl_toplevel_eval_flex at /home/ufechner/julia/src/toplevel.c:831
jl_toplevel_eval_flex at /home/ufechner/julia/src/toplevel.c:778
jl_toplevel_eval_in at /home/ufechner/julia/src/builtins.c:633
eval at ./boot.jl:319
jl_apply_generic at /home/ufechner/julia/src/gf.c:2165
macro expansion at ./logging.jl:317 [inlined]
exec_options at ./client.jl:224
_start at ./client.jl:427
jl_apply_generic at /home/ufechner/julia/src/gf.c:2165
jl_apply at /home/ufechner/julia/ui/../src/julia.h:1538 [inlined]
true_main at /home/ufechner/julia/ui/repl.c:112
main at /home/ufechner/julia/ui/repl.c:243
__libc_start_main at /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
_start at /home/ufechner/julia/usr/bin/julia (unknown line)
WARNING: importing deprecated binding Base.gamma into DualNumbers.
Test Summary: | Pass  Total
Derivatives   |  214    214
Test Summary:          | Pass  Total
Derivatives (coloring) |   14     14
Test Summary:    | Pass  Total
Container syntax |   36     36
┌ Warning: using similar(f, shape) to call `f` with axes `shape` is deprecated; call `f` directly and/or add methods such that it supports axes
│   caller = similar(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{UnitRange{Int64}},getfield(Main, Symbol("#plus1#14")),Tuple{JuMPArray{Float64,1,Tuple{UnitRange{Int64}},Tuple{Dict{Int64,Int64}}}}}, ::Type{Float64}) at broadcast.jl:193
└ @ Base.Broadcast ./broadcast.jl:193
JuMPArray: Error During Test at /home/ufechner/.julia/packages/JuMP/zqYp/test/containers.jl:90
  Got exception MethodError(Array{Float64,N} where N, ((2:3,),), 0xffffffffffffffff) outside of a @test
  MethodError: no method matching Array{Float64,N} where N(::Tuple{UnitRange{Int64}})
  Closest candidates are:
    Array{Float64,N} where N(::Any) where T<:AbstractArray at abstractarray.jl:22
    Array{Float64,N} where N(!Matched::UndefInitializer, !Matched::Int64) where T at boot.jl:408
    Array{Float64,N} where N(!Matched::UndefInitializer, !Matched::Int64, !Matched::Int64) where T at boot.jl:409
    ...
  Stacktrace:
   [1] Array{Float64,N} where N(::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:22
   [2] similar(::Type, ::Tuple{UnitRange{Int64}}) at ./deprecated.jl:1633
   [3] similar(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{UnitRange{Int64}},getfield(Main, Symbol("#plus1#14")),Tuple{JuMPArray{Float64,1,Tuple{UnitRange{Int64}},Tuple{Dict{Int64,Int64}}}}}, ::Type{Float64}) at ./broadcast.jl:193
   [4] copy at ./broadcast.jl:744 [inlined]
   [5] materialize(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,getfield(Main, Symbol("#plus1#14")),Tuple{JuMPArray{Float64,1,Tuple{UnitRange{Int64}},Tuple{Dict{Int64,Int64}}}}}) at ./broadcast.jl:724
   [6] macro expansion at /home/ufechner/.julia/packages/JuMP/zqYp/test/containers.jl:103 [inlined]
   [7] macro expansion at /home/ufechner/julia/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1080 [inlined]
   [8] top-level scope at /home/ufechner/.julia/packages/JuMP/zqYp/test/containers.jl:91
   [9] include at ./boot.jl:317 [inlined]
   [10] include_relative(::Module, ::String) at ./loading.jl:1050
   [11] include(::Module, ::String) at ./sysimg.jl:29
   [12] include(::String) at ./client.jl:393
   [13] top-level scope at none:0
   [14] include at ./boot.jl:317 [inlined]
   [15] include_relative(::Module, ::String) at ./loading.jl:1050
   [16] include(::Module, ::String) at ./sysimg.jl:29
   [17] include(::String) at ./client.jl:393
   [18] top-level scope at none:0
   [19] eval(::Module, ::Any) at ./boot.jl:319
   [20] macro expansion at ./logging.jl:317 [inlined]
   [21] exec_options(::Base.JLOptions) at ./client.jl:224
   [22] _start() at ./client.jl:427
Test Summary: | Pass  Error  Total
JuMPArray     |    7      1      8
ERROR: LoadError: LoadError: Some tests did not pass: 7 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/ufechner/.julia/packages/JuMP/zqYp/test/containers.jl:90
in expression starting at /home/ufechner/.julia/packages/JuMP/zqYp/test/runtests.jl:55
ERROR: Package JuMP errored during testing
```
Any idea?

**Comment by mlubin** [comment] 2018-07-27 21:08
This is a duplicate of #1177. JuMPArray needs a nontrivial amount of work to be compatible with 0.7, analogous to https://github.com/JuliaArrays/AxisArrays.jl/pull/131.

The first error there is concerning though, looks like a crash in Julia's compiler.

**Comment by mlubin** [comment] 2018-08-19 00:15
JuMP is passing tests on Julia 0.7 now

**Closed by mlubin** 2018-08-19 00:15 UTC
