### ISSUE TITLE
CoinOptServices will not compile on Julia 0.6.0

### ISSUE THREAD

**Issue by leoliberti** [JuliaOpt/JuMP.jl#1101] opened 2017-09-09 16:32 UTC
Hi, 

While trying to install CoinOptServices on JuMP 0.18.0 on Julia 0.6.0 (both on Ubuntu 17.04 and on Windows 10; and, on Linux, both with the precompiled Linux x64 executable as well as with a freshly compiled one) I run into an issue where ./configure fails on Bonmin. 

See the following excerpt of the output obtained from running "julia build.jl" into ~/.julia/v0.6/CoinOptServices/deps. I am also copying the whole output of running the command Pkg.build("CoinOptServices") in Julia (I cannot tell whether it's the same cause of failure). Both outputs were obtained on Ubuntu 17.04: not with the stock Ubuntu julia distribution (since it's only 0.4.7), but with a freshly downloaded precompiled Linux binary distribution julia-903644385b. As far as I remember, the behaviour on a freshly compiled julia 0.6.0 on Linux Ubuntu 17.04 is the same.

Any help is appreciated. 

Yours,

Leo 

=== julia build.jl ===
configure: configuring in Bonmin
configure: running /bin/bash '../../Bonmin/configure' --prefix=/home/liberti/.julia/v0.6/CoinOptServices/deps/usr  '--prefix=/home/liberti/.julia/v0.6/CoinOptServices/deps/usr' '--enable-dependency-linking' 'coin_skip_warn_cflags=yes' 'coin_skip_warn_cxxflags=yes' 'coin_skip_warn_fflags=yes' '--with-coinutils-lib=-L/usr/local/lib -lCoinUtils' '--with-coinutils-incdir=/usr/local/lib/../include/coin' '--with-osi-lib=-L/usr/local/lib -lOsi -lCoinUtils' '--with-osi-incdir=/usr/local/lib/../include/coin' '--with-clp-lib=-L/usr/local/lib -lClp -lOsiClp' '--with-clp-incdir=/usr/local/lib/../include/coin' '--with-cgl-lib=-L/usr/local/lib -lCgl' '--with-cgl-incdir=/usr/local/lib/../include/coin' '--with-cbc-lib=-L/usr/local/lib -lCbc' '--with-cbc-incdir=/usr/local/lib/../include/coin' '--with-blas=-L/usr/local/lib -lcoinblas' '--with-lapack=-L/usr/local/lib -lcoinlapack' '--with-mumps-lib=-L/usr/local/lib -lcoinmumps' '--with-ipopt-lib=-L/usr/local/lib -lipopt' --cache-file=/dev/null --srcdir=../../Bonmin
checking build system type... x86_64-unknown-linux-gnu
checking for svnversion... yes
checking whether we want to compile in debug mode... no
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
configure: C compiler options are: -O3 -pipe -DNDEBUG    -DBONMIN_BUILD
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether C++ compiler g++ works... yes
configure: C++ compiler options are: -O3 -pipe -DNDEBUG    -DBONMIN_BUILD
checking for egrep... grep -E
checking whether ln -s works... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking dependency style of g++... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
../../Bonmin/configure: line 5284: cd: /home/liberti/.julia/v0.6/CoinOptServices/deps/usr: No such file or directory
configure: Using libtool script in directory ..
checking if library version is set... 12:2:8
checking for pkg-config... pkg-config
checking pkg-config is at least version 0.16.0... yes
checking for COIN-OR package CoinDepend... not given: No package 'cbc' found
No package 'osi-clp' found
No package 'ipopt' found
configure: error: Required package Cbc or Ipopt not available.
configure: error: /bin/bash '../../Bonmin/configure' failed for Bonmin

=== Pkg.build("CoinOptServices") ===
ulia> Pkg.build("CoinOptServices")
INFO: Building Cbc
INFO: Building Ipopt
INFO: Building LightXML
INFO: Building CoinOptServices
WARNING: Method definition @checked_lib(ANY, ANY) in module __anon__ at /home/liberti/.julia/v0.6/Cbc/deps/deps.jl:7 overwritten at /home/liberti/.julia/v0.6/Ipopt/deps/deps.jl:7.
INFO: Attempting to Create directory /home/liberti/.julia/v0.6/CoinOptServices/deps/downloads
INFO: Directory /home/liberti/.julia/v0.6/CoinOptServices/deps/downloads already created
INFO: Downloading file http://www.coin-or.org/download/source/OS/OS-2.9.2.tgz
INFO: Done downloading file http://www.coin-or.org/download/source/OS/OS-2.9.2.tgz
INFO: Attempting to Create directory /home/liberti/.julia/v0.6/CoinOptServices/deps/src
INFO: Directory /home/liberti/.julia/v0.6/CoinOptServices/deps/src already created
INFO: Attempting to Create directory /home/liberti/.julia/v0.6/CoinOptServices/deps
INFO: Directory /home/liberti/.julia/v0.6/CoinOptServices/deps already created
INFO: Path /home/liberti/.julia/v0.6/CoinOptServices/deps/src/OS-2.9.2 already created
INFO: Attempting to Create directory /home/liberti/.julia/v0.6/CoinOptServices/deps/src/OS-2.9.2/build
INFO: Directory /home/liberti/.julia/v0.6/CoinOptServices/deps/src/OS-2.9.2/build already created
INFO: Changing Directory to /home/liberti/.julia/v0.6/CoinOptServices/deps/src/OS-2.9.2/build
INFO: Changing Directory to /home/liberti/.julia/v0.6/CoinOptServices/deps/src/OS-2.9.2/build
../configure: line 5879: cd: /home/liberti/.julia/v0.6/CoinOptServices/deps/usr: No such file or directory
../configure: line 21807: coin_has_data/sample=notGiven: No such file or directory
../../Vol/configure: line 5291: cd: /home/liberti/.julia/v0.6/CoinOptServices/deps/usr: No such file or directory
../../DyLP/configure: line 5279: cd: /home/liberti/.julia/v0.6/CoinOptServices/deps/usr: No such file or directory
../../SYMPHONY/configure: line 5344: cd: /home/liberti/.julia/v0.6/CoinOptServices/deps/usr: No such file or directory
configure: WARNING: unrecognized options: --enable-dependency-linking, --with-coinutils-lib, --with-coinutils-incdir, --with-osi-lib, --with-osi-incdir, --with-clp-lib, --with-clp-incdir, --with-cgl-lib, --with-cgl-incdir, --with-cbc-lib, --with-cbc-incdir, --with-blas, --with-lapack, --with-mumps-lib, --with-ipopt-lib
configure: WARNING: unrecognized options: --enable-dependency-linking, --with-coinutils-lib, --with-coinutils-incdir, --with-osi-lib, --with-osi-incdir, --with-clp-lib, --with-clp-incdir, --with-cgl-lib, --with-cgl-incdir, --with-cbc-lib, --with-cbc-incdir, --with-blas, --with-lapack, --with-mumps-lib, --with-ipopt-lib
../../Bonmin/configure: line 5284: cd: /home/liberti/.julia/v0.6/CoinOptServices/deps/usr: No such file or directory
configure: error: Required package Cbc or Ipopt not available.
configure: error: /bin/bash '../../Bonmin/configure' failed for Bonmin
============================[ ERROR: CoinOptServices ]============================

LoadError: failed process: Process(setenv(`../configure --prefix=/home/liberti/.julia/v0.6/CoinOptServices/deps/usr --enable-dependency-linking coin_skip_warn_cflags=yes coin_skip_warn_cxxflags=yes coin_skip_warn_fflags=yes '--with-coinutils-lib=-L/usr/local/lib -lCoinUtils' --with-coinutils-incdir=/usr/local/lib/../include/coin '--with-osi-lib=-L/usr/local/lib -lOsi -lCoinUtils' --with-osi-incdir=/usr/local/lib/../include/coin '--with-clp-lib=-L/usr/local/lib -lClp -lOsiClp' --with-clp-incdir=/usr/local/lib/../include/coin '--with-cgl-lib=-L/usr/local/lib -lCgl' --with-cgl-incdir=/usr/local/lib/../include/coin '--with-cbc-lib=-L/usr/local/lib -lCbc' --with-cbc-incdir=/usr/local/lib/../include/coin '--with-blas=-L/usr/local/lib -lcoinblas' '--with-lapack=-L/usr/local/lib -lcoinlapack' '--with-mumps-lib=-L/usr/local/lib -lcoinmumps' '--with-ipopt-lib=-L/usr/local/lib -lipopt'`,String["PATH=/home/liberti/bin:/home/liberti/.local/bin:/usr/local/MATLAB/R2012a/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path", "QT_ACCESSIBILITY=1", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_DESKTOP=ubuntu", "LIBGL_ALWAYS_SOFTWARE=1", "XDG_SESSION_TYPE=x11", "USER=liberti", "QT_IM_MODULE=ibus", "LESSCLOSE=/usr/bin/lesspipe %s %s", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg", "GNOME_SESSION_XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0", "GDMSESSION=ubuntu", "CLUTTER_IM_MODULE=xim", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop", "LESSOPEN=| /usr/bin/lesspipe %s", "SHELL=/bin/bash", "XAUTHORITY=/home/liberti/.Xauthority", "XDG_MENU_PREFIX=gnome-", "GTK_MODULES=gail:atk-bridge:unity-gtk-module", "GTK_IM_MODULE=ibus", "MANAGERPID=1780", "SESSION_MANAGER=local/wafer:@/tmp/.ICE-unix/2158,unix/wafer:/tmp/.ICE-unix/2158", "QT_QPA_PLATFORMTHEME=appmenu-qt5", "XMODIFIERS=@im=ibus", "HOME=/home/liberti", "TERM=xterm-256color", "COLORTERM=truecolor", "VTE_VERSION=4402", "GTK2_MODULES=overlay-scrollbar", "INVOCATION_ID=f8dbd814a0a640068de012738362e4eb", "COMPIZ_CONFIG_PROFILE=ubuntu", "IM_CONFIG_PHASE=1", "XDG_CURRENT_DESKTOP=Unity:Unity7", "LANG=en_US.UTF-8", "SHLVL=2", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "LOGNAME=liberti", "XDG_RUNTIME_DIR=/run/user/1000", "OLDPWD=/home/liberti/.julia/v0.6/CoinOptServices/deps", "GDM_LANG=en_US", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "DESKTOP_SESSION=ubuntu", "_=/usr/local/bin/julia", "GPG_AGENT_INFO=/home/liberti/.gnupg/S.gpg-agent:0:1:", "PWD=/home/liberti", "DISPLAY=:0", "COMPIZ_BIN_PATH=/usr/bin/", "LANGUAGE=en_US", "XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/liberti", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0", "WINDOWID=58720262", "MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path", "JOURNAL_STREAM=8:32337", "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig", "SSH_AGENT_LAUNCHER=gnome-keyring", "QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1", "QT4_IM_MODULE=xim", "LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
while loading /home/liberti/.julia/v0.6/CoinOptServices/deps/build.jl, in expression starting on line 71

==================================================================================

=================================[ BUILD ERRORS ]=================================

WARNING: CoinOptServices had build errors.

 - packages with build errors remain installed in /home/liberti/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("CoinOptServices")`
 - build a single package by running its `deps/build.jl` script

==================================================================================

**Comment by mlubin** [comment] 2017-09-10 19:26
> checking for COIN-OR package CoinDepend... not given: No package 'cbc' found

How is Cbc installed? What's the content of `~/.julia/v0.6/Cbc/deps/deps.jl`?

**Comment by leoliberti** [comment] 2017-09-21 20:17
Hi Miles, 

W.r.t. your question "how is CBC installed?", in my system the Cbc/Clp/Bonmin/Couenne binaries are all created by a unique Couenne installation, and the binaries are symlinks under /usr/local/bin. But I would have thought this irrelevant, since it appears that julia downloads and builds its own private copies of those programs... doesn't it?
As for "What's the content of ~/.julia/v0.6/Cbc/deps/deps.jl", I'm attaching it here -- it's the stock one, unchanged from installation.

Thanks for your help
Yours,
Leo
----


    On Sunday, September 10, 2017 9:26 PM, Miles Lubin <notifications@github.com> wrote:
 

 
checking for COIN-OR package CoinDepend... not given: No package 'cbc' found
How is Cbc installed? What's the content of ~/.julia/v0.6/Cbc/deps/deps.jl?—

**Comment by mlubin** [comment] 2017-09-22 22:47
@leoliberti, attachments do not come through on email replies to GitHub, you could paste the content or use the web interface. Julia's Cbc.jl can find system-installed copies as well, which could cause some confusion in the build scripts for CoinOptServices. I cannot reproduce the issue.

**Comment by mlubin** [comment] 2017-11-25 21:30
Closing, this is not a JuMP issue, and I can't reproduce it. Please reopen at https://github.com/JuliaOpt/CoinOptServices.jl/issues if still relevant.

**Closed by mlubin** 2017-11-25 21:30 UTC
