### ISSUE TITLE
Define a variable in Arrays

### ISSUE THREAD

**Issue by stono1314** [JuliaOpt/JuMP.jl#1580] opened 2018-11-02 18:59 UTC
I am not sure why this is happening and the error message, humorous as it is, is not helping. LL and 1 : nL are basically the same thing, but there is a error when I put LL as the range.
```julia
julia> LL == 1 : nL
true

julia> @variable(m, f[LL])
ERROR: MethodError: no method matching _to_cartesian(::Type{JuMP.JuMPArray{Variable,1,Tuple{UnitRange{Int64}}}},
::Type{Tuple{UnitRange{Int64}}}, ::Tuple{DataType})
The applicable method may be too new: running in world age 28374, while current world is 32483.
Closest candidates are:
  _to_cartesian(::Any, ::Any, ::Any...) at C:\Users\Yushi\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\JuMP\Xvn0n\src\JuMPArray.jl:63 (method too new to be called from this world context.)
Stacktrace:
 [1] #s260#3(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at C:\Users\Yushi\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\JuMP\Xvn0n\src\JuMPArray.jl:50
 [2] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at .\boot.jl:506
 [3] top-level scope at C:\Users\Yushi\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\JuMP\Xvn0n\src\macros.jl:1259

julia> @variable(m, f[1 : nL])
┌ Warning: A variable or constraint named f is already attached to this model. If creating variables programmatically, use the anonymous variable syntax x = @variable(m, [1:N], ...).
└ @ JuMP C:\Users\Yushi\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\JuMP\Xvn0n\src\JuMP.jl:852
12-element Array{Variable,1}:
 f[1]
 f[2]
 f[3]
 f[4]
 f[5]
 f[6]
 f[7]
 f[8]
 f[9]
 f[10]
 f[11]
 f[12]
```
Edit(odow): formatting.

**Comment by odow** [comment] 2018-11-02 19:41
I cannot reproduce this. What version of JuMP are you running? 

Please provide a reproducible example  https://stackoverflow.com/help/mcve.

**Comment by stono1314** [comment] 2018-11-02 22:35
Thanks for the reply. I was and am using 0.18.4.  I am not sure what I did. I just wanted to create a small example but everything works now.

**Comment by blegat** [comment] 2018-11-02 23:15
It is unclear what `LL` actually *is* and how it was constructed

**Comment by odow** [comment] 2018-11-07 18:14
Closing as this isn't reproducible. Please re-open with a minimal working example if you run into this again.

**Closed by odow** 2018-11-07 18:14 UTC
