### ISSUE TITLE
Integer solution with Gurobi and continuous solution with Cbc for a same IP formulation

### ISSUE THREAD

**Issue by Okidoki72** [JuliaOpt/JuMP.jl#1327] opened 2018-06-06 17:59 UTC
With the following code written by one of my students:
```julia
using JuMP
using Cbc
using Gurobi

d = [15,14 ,14, 17, 22, 20 ,10 ,20 ,18 ,15 ,20 ,20]
periods = length(d)

#m = Model(solver = CbcSolver())
m = Model(solver = GurobiSolver())

@variable(m,x[1:12]>=0,Int)
@objective(m, Min, sum(x))

for i in 0:periods-1
    @constraint(m, x[rem(i+6,periods)+1]+x[rem(i+5,periods)+1]+x[rem(i+3,periods)+1]+x[rem(i+2,periods)+1]>=d[rem(i+6,periods)+1])
end

print(m)

solve(m)

status=solve(m)
println(getobjectivevalue(m))
println(getvalue(x))
```
When Gurobi is used to solve the model, we get an integer solution:
```
[7.0, 13.0, 7.0, 2.0, 0.0, 0.0, 6.0, 12.0, 7.0, 2.0, 0.0, 1.0]
```
However, when Cbc is used, we get a continuous solution when it should be integer:
```
[3.5, 10.5, 0.0, 2.0, 6.0, 3.5, 11.5, 8.5, 0.0, 0.0, 0.0, 11.5]
```

**Comment by Okidoki72** [comment] 2018-06-06 18:10
It seems that Cbc fails to build with Julia 0.6.2, which would explain this issue.

**Comment by blegat** [comment] 2018-06-06 18:12
@Okidoki72 Let us know if there is another issue. Note that [the discourse forum](https://discourse.julialang.org/) is more appropriate for questions like these.

**Comment by joehuchette** [comment] 2018-06-06 18:20
I can reproduce this, so I'm reopening. I did a bit of digging and it appears JuMP is communicating the variable types to the solver correctly, so this is likely a bug with Cbc.

**Comment by mlubin** [comment] 2018-06-06 19:40
It wouldn't be surprising at all if this is a bug in Cbc. @chriscoey and I observed similar behavior with Cbc ignoring integrality constraints when working on Pajarito.

**Comment by Okidoki72** [comment] 2018-06-06 19:58
Thank you all for your feedback. It confirms my suspicions about Cbc.

**Comment by mlubin** [comment] 2018-06-15 11:44
Closing since there's no evidence of a JuMP issue. I would recommend following up on the Cbc mailing list if you're concerned about this bug.

**Closed by mlubin** 2018-06-15 11:44 UTC
