### ISSUE TITLE
Creating arrays of variables with UInt bounds

### ISSUE THREAD

**Issue by allbits** [JuliaOpt/JuMP.jl#857] opened 2016-10-02 21:55 UTC
The following does not work.

function build()
   m = Model()
   n::UInt = 4
   @variable(m,x[1:n])
end

Changing UInt to Int works.

**Comment by joehuchette** [comment] 2016-10-05 15:08
This is a surprisingly subtle issue, caused by the fact that ``length(1:UInt(4))`` returns a ``UInt(4)`` (rather than an integer, as is usually the case). I believe there's an open issue in the julia repo for this.

**Comment by joehuchette** [comment] 2016-10-05 20:42
Closed by #862, thanks for reporting

**Closed by joehuchette** 2016-10-05 20:42 UTC
Labels: bug
