### ISSUE TITLE
Mixed Integer SOCP through Gurobi, Doesn't except initial value?

### ISSUE THREAD

**Issue by brianhan5858** [JuliaOpt/JuMP.jl#832] opened 2016-08-16 07:47 UTC
Hi Julia JuMP team:

I have a question that I think it might be caused by a bug. 

In short I have a mixed integer SOCP. It is mixed because there is a continuous decision variable on the RHS of a SOC constraint. I conjecture that JuMP always tells gurobi solver set 0 as the initial on the RHS of a SOC constraint, which we cannot change by using setValue().

My model is as followed with a little numerical example

`using JuMP
using Gurobi

# Numerical Example
N = 10;
M =  [0.0  1.0
 1.0  0.0
 1.0  0.0
 1.0  0.0
 0.0  1.0
 1.0  0.0
 0.0  1.0
 0.0  1.0
 1.0  0.0
 1.0  0.0];
L = [0.97557  0.0
 -1.02504  0.0];

# Model 
m = Model(solver = GurobiSolver(Heuristics=0.0))
    @defVar(m, z[j = 1:N], Bin)
    @defVar(m, t )
    @setObjective(m, Max, sum(M'*z) - 3* t)
    @addConstraint( m, sum(z) <= 5)
    @addConstraint(m, norm(L'*M'*z) <= t) 
`

When I feed an initial value of z as zeros, the model does accept it. 
`setValue(z, zeros(N))
solve(m)`
And the results is like this
> Loaded MIP start with objective 0

The solver gives an optimal value.
`OPT = 
[1.0
 0.0
 0.0
 1.0
 0.0
 1.0
 1.0
 0.0
 0.0
 0.0]`
 Here the problem comes. When I set the initial value of anything but zeros. The results will report 
sth like this:
> MIP start did not produce a new incumbent solution
MIP start violates constraint R11 by 0.10 

To make sure that the initial value that I feed is indeed feasible and is better than any initial guess, I pick the initial value to be OPT. Also to make sure the observation that we see is not observe is not cause by anything related to code, I build the same model again and run it gain. That is to say to run the model building code once again, but set the intial value to be OPT, and also set the intial value for t to make the SOC constraint equal. 
`setValue(z, OPT)
setValue(t, norm(L'*M'*OPT))
`
I will still get:
> MIP start did not produce a new incumbent solution
MIP start violates constraint R11 by 0.10 . 

R11 constraint is exactly the SOC constraint, and the value of 0.10 is the  always the value of 
norm(L'*M'*OPT), which is 0.09893999999999979 in this case. 

I have tried several other initial value, the reported constraint violation is always this value.

So my conjecture is that no matter what I do in JUMP,  JUMP always automatically tells Gurobi to start the RHS (t here) of SOC constraint from 0. Even though when I set the initial t to be a feasible one, it always starts with 0. That explains why gurobi always say the constraint is violated when I pick initial z to be sth other than zeros.

What do you think?

Thanks so much for your help!
Really appreciate it.

Best,
Brian

**Comment by vgupta1** [comment] 2016-08-16 12:53
Hi Brian, 
It seems that #784 is related to this issue.  In particular, if I follow the advice there and replace
``` julia
@addConstraint(m, norm(L'M'z) <= t) 
```
in your code with 

``` julia
#make the norm constraint explicit
M_L = [-1.02504  0.0
        0.97557  0.0
        0.97557  0.0
        0.97557  0.0
        -1.02504  0.0
        0.97557  0.0
        -1.02504  0.0
        -1.02504  0.0
        0.97557  0.0
        0.97557  0.0]

@defVar(m, xs[1:2])
for jx = 1:2
    @addConstraint(m, sum{M_L[ix, jx]*z[ix], ix = 1:10} == xs[jx])
end
@addConstraint(m, t^2 >= xs[1]^2 + xs[2]^2)
```
it seems from the output that Gurobi does use the solution correctly.  (There's also probably a cleaner way to write the above code.)

**Comment by mlubin** [comment] 2016-08-16 14:03
Yes, this is a duplicate of https://github.com/JuliaOpt/JuMP.jl/issues/784. If you'd like to take a stab at adding this feature, the relevant code is at https://github.com/JuliaOpt/MathProgBase.jl/blob/master/src/SolverInterface/lpqp_to_conic.jl, and we'd be happy to answer any questions you have in the process.
CC @brad-sturt

**Closed by mlubin** 2016-08-16 14:03 UTC
