### ISSUE TITLE
NAN when invoking SDP constraint

### ISSUE THREAD

**Issue by BenRapone** [JuliaOpt/JuMP.jl#981] opened 2017-03-02 23:28 UTC
Using Mosek as a solver I am getting seemingly random NANs after I impose a SDP constraint on a relaxation of a quadratic system. The same model run through Convex does not give me issues though frighteningly longer run times. The systems are all contrived around random predefined solutions so primal infeasibility should not be an issue. I modified the code attached to give you a particular example of a system that produces a NAN. 

Ben
[NANEx.txt](https://github.com/JuliaOpt/JuMP.jl/files/815362/NANEx.txt)

**Comment by mlubin** [comment] 2017-03-03 01:51
I can't reproduce this issue locally, and I don't see anything wrong with how JuMP is generating the model. Convex.jl does not generate identical models, so different behavior is not immediately suggestive of an issue with JuMP. You may try contacting Mosek for support if the solver is giving unexpected answers.

**Comment by mlubin** [comment] 2017-05-15 02:04
Closing this as there's no evidence so far of an issue with JuMP.

**Closed by mlubin** 2017-05-15 02:04 UTC
